[phases.setup]
nixPkgs = ["dotnet-sdk-8"]

[phases.build]
cmds = [
  "cd backend",
  "dotnet restore",
  "dotnet publish src/API/API.csproj -c Release -o /app/publish"
]

[start]
cmd = "dotnet /app/publish/API.dll"
